spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/user_registration
    password: '2444'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
server:
  port: 9000